s1a:((J_b*M_b*R_w^3+J_b*M_b*R_b*R_w^2)*g*sin(phi_2)+((M_b*R_b^2+J_b)*R_w^2+2*M_b*R_b^3*R_w+M_b*R_b^4)*T_w)/(J_b*M_b*R_w^4+2*J_b*M_b*R_b*R_w^3+((J_w+J_b)*M_b*R_b^2+J_b*J_w)*R_w^2+2*J_w*M_b*R_b^3*R_w+J_w*M_b*R_b^4);

s2a:((J_b*M_b*R_w^3+J_b*M_b*R_b*R_w^2+J_w*M_b*R_b^2*R_w+J_w*M_b*R_b^3)*g*sin(phi_2)+J_b*R_w^2*T_w)/(J_b*M_b*R_w^4+2*J_b*M_b*R_b*R_w^3+((J_w+J_b)*M_b*R_b^2+J_b*J_w)*R_w^2+2*J_w*M_b*R_b^3*R_w+J_w*M_b*R_b^4);

s1b:((J_b*M_b*R_w^3+J_b*M_b*R_b*R_w^2)*g*sin((R_w*phi_w+R_b*phi_b)/R_w)+((M_b*R_b^2+J_b)*R_w^2+2*M_b*R_b^3*R_w+M_b*R_b^4)*T_w)/(J_b*M_b*R_w^4+2*J_b*M_b*R_b*R_w^3+((J_w+J_b)*M_b*R_b^2+J_b*J_w)*R_w^2+2*J_w*M_b*R_b^3*R_w+J_w*M_b*R_b^4);

s2b:((J_b*M_b*R_w^3+J_b*M_b*R_b*R_w^2+J_w*M_b*R_b^2*R_w+J_w*M_b*R_b^3)*g*sin((R_w*phi_w+R_b*phi_b)/R_w)+J_b*R_w^2*T_w)/(J_b*M_b*R_w^4+2*J_b*M_b*R_b*R_w^3+((J_w+J_b)*M_b*R_b^2+J_b*J_w)*R_w^2+2*J_w*M_b*R_b^3*R_w+J_w*M_b*R_b^4);

s1c:(%o31) ((J_b*M_b*R_w^3+J_b*M_b*R_b*R_w^2)*g*sin(phi_2)+((-M_b*R_b^2-J_b)*R_w^2-2*M_b*R_b^3*R_w-M_b*R_b^4)*d_w*omega_w+((M_b*R_b^2+J_b)*R_w^2+2*M_b*R_b^3*R_w+M_b*R_b^4)*T_w)/(J_b*M_b*R_w^4+2*J_b*M_b*R_b*R_w^3+((J_w+J_b)*M_b*R_b^2+J_b*J_w)*R_w^2+2*J_w*M_b*R_b^3*R_w+J_w*M_b*R_b^4);

s2c:((J_b*M_b*R_w^3+J_b*M_b*R_b*R_w^2+J_w*M_b*R_b^2*R_w+J_w*M_b*R_b^3)*g*sin(phi_2)-J_b*R_w^2*d_w*omega_w+J_b*R_w^2*T_w)/(J_b*M_b*R_w^4+2*J_b*M_b*R_b*R_w^3+((J_w+J_b)*M_b*R_b^2+J_b*J_w)*R_w^2+2*J_w*M_b*R_b^3*R_w+J_w*M_b*R_b^4);

s1d:-(((M_b*R_b^2+J_b)*R_w^2+2*M_b*R_b^3*R_w+M_b*R_b^4)*d_w*w_w+(-J_b*M_b*R_w^3-J_b*M_b*R_b*R_w^2)*g*sin((R_w*phi_w+R_b*phi_b)/R_w)+((-M_b*R_b^2-J_b)*R_w^2-2*M_b*R_b^3*R_w-M_b*R_b^4)*T_w)/(J_b*M_b*R_w^4+2*J_b*M_b*R_b*R_w^3+((J_w+J_b)*M_b*R_b^2+J_b*J_w)*R_w^2+2*J_w*M_b*R_b^3*R_w+J_w*M_b*R_b^4);

s2d:(J_b*R_w^2*d_w*w_w+(-J_b*M_b*R_w^3-J_b*M_b*R_b*R_w^2-J_w*M_b*R_b^2*R_w-J_w*M_b*R_b^3)*g*sin((R_w*phi_w+R_b*phi_b)/R_w)-J_b*R_w^2*T_w)/(J_b*M_b*R_w^4+2*J_b*M_b*R_b*R_w^3+((J_w+J_b)*M_b*R_b^2+J_b*J_w)*R_w^2+2*J_w*M_b*R_b^3*R_w+J_w*M_b*R_b^4);